import { describe, expect, it } from "bun:test";
import { z } from "zod";
import { renderEventCatalog } from "./eventCatalog";
import { buildEventJsonSchemas } from "./schemaExport";

describe("renderEventCatalog", () => {
  it("renders a 'No event schemas found.' body for zero events", () => {
    const markdown = renderEventCatalog({ events: {} });

    expect(markdown).toContain("# Event Catalog");
    expect(markdown).toContain("_Generated by `typetrack docs`._");
    expect(markdown).toContain("No event schemas found.");
  });

  it("renders '_No payload._' for a no-payload event (z.undefined())", () => {
    const markdown = renderEventCatalog(buildEventJsonSchemas({ app_opened: z.undefined() }));

    expect(markdown).toContain("## app_opened");
    expect(markdown).toContain("_No payload._");
    expect(markdown).not.toContain("| Property |");
  });

  it("renders '_No payload._' for a schema with no enumerable properties (empty object)", () => {
    const markdown = renderEventCatalog(buildEventJsonSchemas({ empty_event: z.object({}) }));

    expect(markdown).toContain("## empty_event");
    expect(markdown).toContain("_No payload._");
  });

  it("renders a table with correct Required column values for required and optional properties", () => {
    const markdown = renderEventCatalog(
      buildEventJsonSchemas({
        signup_completed: z.object({
          plan: z.string(),
          referralCode: z.string().optional(),
        }),
      }),
    );

    expect(markdown).toContain("| Property | Type | Required | Description |");
    expect(markdown).toContain("| plan | string | Yes |  |");
    expect(markdown).toContain("| referralCode | string | No |  |");
  });

  it("renders a property's .describe() text in the Description column, and leaves it empty when unset", () => {
    const markdown = renderEventCatalog(
      buildEventJsonSchemas({
        page_viewed: z.object({
          path: z.string().describe("the page's pathname"),
          referrer: z.string().optional(),
        }),
      }),
    );

    expect(markdown).toContain("| path | string | Yes | the page's pathname |");
    expect(markdown).toContain("| referrer | string | No |  |");
  });

  it("escapes a literal '|' character in a description so it can't break the table", () => {
    const markdown = renderEventCatalog(
      buildEventJsonSchemas({
        purchase_completed: z.object({
          plan: z.string().describe("free | pro | enterprise"),
        }),
      }),
    );

    expect(markdown).toContain("free \\| pro \\| enterprise");
    // The raw, unescaped separator must not appear anywhere in the table row.
    expect(markdown).not.toContain("free | pro | enterprise |");
  });

  it("falls back to 'unknown' for a property with no single top-level type (a union)", () => {
    const markdown = renderEventCatalog(
      buildEventJsonSchemas({
        value_changed: z.object({
          value: z.union([z.string(), z.number()]),
        }),
      }),
    );

    expect(markdown).toContain("| value | unknown | Yes |  |");
  });

  it("preserves input key order across multiple events, not sorted", () => {
    const markdown = renderEventCatalog(
      buildEventJsonSchemas({
        zeta_event: z.undefined(),
        alpha_event: z.undefined(),
        middle_event: z.undefined(),
      }),
    );

    const zetaIndex = markdown.indexOf("## zeta_event");
    const alphaIndex = markdown.indexOf("## alpha_event");
    const middleIndex = markdown.indexOf("## middle_event");

    expect(zetaIndex).toBeGreaterThanOrEqual(0);
    expect(zetaIndex).toBeLessThan(alphaIndex);
    expect(alphaIndex).toBeLessThan(middleIndex);
  });
});
