import type { EventJsonSchemas } from "./schemaExport";

interface JsonSchemaProperty {
  type?: unknown;
  description?: unknown;
}

interface JsonSchemaObject {
  properties?: Record<string, unknown>;
  required?: unknown;
}

// Escapes a literal `|` character so it can never break a rendered Markdown
// table's column structure.
function escapeTableCell(value: string): string {
  return value.replaceAll("|", "\\|");
}

// Pure: renders issue 001's `EventJsonSchemas` (`{ events: { [name]:
// JSONSchema } }`) as a human-readable Markdown event catalog. Never throws
// on any well-formed `z.toJSONSchema()` output -- falls back to `"unknown"`
// for a property with no single top-level `type` (e.g. a `oneOf`/`anyOf`
// union) rather than throwing.
export function renderEventCatalog(eventJsonSchemas: EventJsonSchemas): string {
  const lines: string[] = ["# Event Catalog", "", "_Generated by `typetrack docs`._", ""];

  const entries = Object.entries(eventJsonSchemas.events);
  if (entries.length === 0) {
    lines.push("No event schemas found.");
    return `${lines.join("\n")}\n`;
  }

  for (const [eventName, rawSchema] of entries) {
    lines.push(`## ${eventName}`, "");
    lines.push(...renderEventBody(rawSchema));
    lines.push("");
  }

  // Drop the trailing blank line added after the last event, then end the
  // file with exactly one trailing newline.
  while (lines.length > 0 && lines[lines.length - 1] === "") lines.pop();
  return `${lines.join("\n")}\n`;
}

function renderEventBody(rawSchema: unknown): string[] {
  const schema = (rawSchema ?? {}) as JsonSchemaObject;
  const properties = schema.properties;
  const propertyNames = properties ? Object.keys(properties) : [];

  if (propertyNames.length === 0) {
    return ["_No payload._"];
  }

  const required = new Set(Array.isArray(schema.required) ? (schema.required as unknown[]) : []);

  const lines: string[] = ["| Property | Type | Required | Description |", "| --- | --- | --- | --- |"];

  for (const name of propertyNames) {
    const property = (properties?.[name] ?? {}) as JsonSchemaProperty;
    const type = typeof property.type === "string" ? property.type : "unknown";
    const isRequired = required.has(name) ? "Yes" : "No";
    const description = typeof property.description === "string" ? property.description : "";

    lines.push(
      `| ${escapeTableCell(name)} | ${escapeTableCell(type)} | ${isRequired} | ${escapeTableCell(description)} |`,
    );
  }

  return lines;
}
